version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    image: '${REGISTRY_HOST}${REGISTRY_URI}:${TAG}'
    ports:
      - '3000:3000'
    env_file:
      - .env
    